version: '3.9'

services:

  back-end:
    restart: always
    container_name: back-end
    build:
      dockerfile: Dockerfile
      context: ./back-end/
    ports:
      - 8000:8000
    volumes:
      - ./back-end/src:/app/src
    # environment:
    #   - DB_HOST=db
    #   - DB_NAME=shopping-cart
    #   - DB_USER=mobin
    #   - DB_PASS=mobinmobin
    # depends_on:
    #   - db

    command: >
      sh -c "python3 /app/src/manage.py makemigrations &&
            /app/src/manage.py migrate &&
            /app/src/manage.py test &&
            /app/src/manage.py runserver 0:8000"
  
#   front-end:
#     restart: always
# #    command : npm start
#     container_name: front-end

#     build:
#       context: ./front-end/
#       dockerfile: Dockerfile

#     ports:
#       - "3000:3000"
#       - "3001:3001"

#     stdin_open: true
#     depends_on:
#       - back-end
#     networks:
#       - db-net  

# networks:
#   db-net:
#     driver: bridge
#   db:
#     container_name: db
#     image: postgres:13
#     environment:
#       - POSTGRES_DB=shopping-cart
#       - POSTGRES_USER=mobin
#       - POSTGRES_PASSWORD=mobinmobin
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/run/postgresql/
#     restart: always

# volumes:
#   postgres_data:
