name: Black CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run Black
      run: black back-end/src
      
    - name: Configure Git
      run: |
          git config --global user.name "mowbish"
          git config --global user.email "mobin.clash.ma@gmail.com"

    - name: Commit formatted code
      run: |
          git add .
          git commit -m "CI Black: change styles of code automatically"
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: ${{ github.ref }}
